Revert `@libsql/load` update
It's causing the following problem with Bun at least:

$ bun i
[0.02ms] ".env"
bun install v1.0.3 (25e69c71)
 + @libsql/client@0.3.5-pre.14

 5 packages installed [1.85s]
whatplan@GAMER:~/code/projects/beth-b2b-saas$ bun dev
$ concurrently "bun run --watch src/main.ts" "bun run uno:dev" "bun run liveReload"
[1] $ bunx unocss --watch
[2] $ bunx beth-stack
[2] 🦊 Livereload running localhost:3001
[1] unocss v0.55.7
[1] ◐ UnoCSS in watch mode...
[0] 28 |   statementRun,
[0] 29 |   statementRowsSync,
[0] 30 |   statementColumns,
[0] 31 |   statementSafeIntegers,
[0] 32 |   rowsNext,
[0] 33 | } = load(__dirname) || require(`@libsql/${target}`);
[0]         ^
[0] TypeError: load is not a function. (In 'load(__dirname)', 'load' is undefined)
[0]       at /home/whatplan/code/projects/beth-b2b-saas/node_modules/libsql/index.js:33:4
      at globalThis (/home/whatplan/code/projects/beth-b2b-saas/node_modules/libsql/index.js:320:29)
[0]       at processTicksAndRejections (:55:76)
[0] 28 |   statementRun,
[0] 29 |   statementRowsSync,
[0] 30 |   statementColumns,
[0] 31 |   statementSafeIntegers,
[0] 32 |   rowsNext,
[0] 33 | } = load(__dirname) || require(`@libsql/${target}`);
[0]         ^
[0] TypeError: load is not a function. (In 'load(__dirname)', 'load' is undefined)
[0]       at /home/whatplan/code/projects/beth-b2b-saas/node_modules/libsql/index.js:33:4
[0]       at globalThis (/home/whatplan/code/projects/beth-b2b-saas/node_modules/libsql/index.js:320:29)
[0]       at processTicksAndRejections (:55:76)
[1] ℹ Watching for changes in src/**/*.{ts,tsx}
^C